using System.Text;

namespace MessageBroker.Infrastructure.Data;

/// <summary>
/// Builds one SQL script that DBAs can review and apply in place of <see cref="SchemaDeployer"/>, for
/// hosts that run with Broker:Database:DeploySchemaOnStartup off. It brings a database at any version
/// up to date: each migration runs only when broker.SchemaVersions has no row for it and then writes
/// that row under the name DbUp uses, so a later DbUp deploy skips it. Programmability scripts are
/// CREATE OR ALTER and always run. Apply it with "sqlcmd -b" so the run stops at the first error.
/// </summary>
public static class ReleaseScript
{
    /// <summary>The sqlcmd variables <see cref="BuildFull"/> reads. Pass every one with -v, even when empty.</summary>
    public static readonly string[] FullScriptVariables = ["DatabaseName", "AdminName", "AdminApiKey", "WebhookAllowedHosts"];

    public static string Build() => AppendSchema(new StringBuilder()
        .AppendLine("-- Internal Message Broker schema release script. Generated; do not edit.")
        .AppendLine("-- Apply with: sqlcmd -b -S <server> -d <database> -i <this file>")).ToString();

    /// <summary>
    /// A full install for a new server: creates the database when it is missing, applies <see cref="Build"/>,
    /// then adds the data the broker needs before anyone can call it, the same data the broker's startup
    /// tasks add from Broker:Bootstrap and Broker:Webhooks:AllowedHosts. It is a sqlcmd script: values come
    /// from -v variables rather than :setvar, because :setvar in a script overrides -v. Re-running it is safe.
    /// </summary>
    public static string BuildFull()
    {
        var sql = new StringBuilder()
            .AppendLine("-- Internal Message Broker full install: database, schema and bootstrap data. Generated by")
            .AppendLine("-- db/build-release-script.ps1 -Full; do not edit.")
            .AppendLine("--")
            .AppendLine("-- From PowerShell, use the wrapper, which passes the values for you:")
            .AppendLine("--   ./db/install-database.ps1 -Server <server> -AdminApiKey <key> -WebhookAllowedHosts hooks.example.com")
            .AppendLine("-- From cmd, run sqlcmd -b connected to any database on the server, passing every variable (\"\" for none):")
            .AppendLine("--   sqlcmd -b -S <server> -i db\\BrokerDb_Full.sql -v DatabaseName=\"BrokerDb\" AdminName=\"broker-admin\"")
            .AppendLine("--          AdminApiKey=\"<key>\" WebhookAllowedHosts=\"hooks.example.com,10.0.0.5\"")
            .AppendLine("--")
            .AppendLine("--   DatabaseName         created when missing.")
            .AppendLine("--   AdminName            the Admin application; empty means broker-admin.")
            .AppendLine("--   AdminApiKey          its first key, from: dotnet run --project src/MessageBroker.Api -- new-api-key")
            .AppendLine("--                        Only the SHA-256 hash is stored. Empty adds no key.")
            .AppendLine("--   WebhookAllowedHosts  comma-separated hosts webhooks may call; empty adds none.")
            .AppendLine("--")
            .AppendLine("-- In SSMS, switch on Query > SQLCMD Mode and add a :setvar line for each variable at the top.")
            .AppendLine("SET QUOTED_IDENTIFIER ON;")
            .AppendLine("GO")
            // sqlcmd stops on this batch when a variable is missing, before anything is created.
            .AppendLine("DECLARE @Variables nvarchar(max) = N'$(DatabaseName)$(AdminName)$(AdminApiKey)$(WebhookAllowedHosts)';")
            .AppendLine("IF LTRIM(RTRIM(N'$(DatabaseName)')) = N'' THROW 50400, N'DatabaseName is required.', 1;")
            .AppendLine("GO")
            .AppendLine("IF DB_ID(N'$(DatabaseName)') IS NULL")
            .AppendLine("BEGIN")
            .AppendLine("    PRINT N'Creating database $(DatabaseName)';")
            .AppendLine("    CREATE DATABASE [$(DatabaseName)];")
            .AppendLine("END")
            .AppendLine("GO")
            .AppendLine("USE [$(DatabaseName)];")
            .AppendLine("GO")
            .AppendLine();
        AppendSchema(sql);
        return sql.AppendLine()
            .AppendLine("-- ===== Bootstrap data")
            .AppendLine("BEGIN TRANSACTION;")
            .AppendLine()
            // Keys are ASCII, so the varchar bytes are the UTF-8 bytes the broker hashes (ApiKeys.Hash).
            .AppendLine("DECLARE @Key varchar(200) = LTRIM(RTRIM('$(AdminApiKey)'));")
            // COALESCE, not ISNULL: ISNULL would cut the default to the length of the empty literal.
            .AppendLine("DECLARE @AdminName nvarchar(100) = COALESCE(NULLIF(LTRIM(RTRIM(N'$(AdminName)')), N''), N'broker-admin');")
            .AppendLine("IF @Key = ''")
            .AppendLine("    PRINT N'AdminApiKey is empty, so no Admin key was added. Set Broker:Bootstrap:AdminApiKey instead.';")
            .AppendLine("ELSE IF LEN(@Key) < 18 OR LEFT(@Key, 4) COLLATE Latin1_General_BIN2 <> 'mbk_' OR SUBSTRING(@Key, 17, 1) <> '_'")
            .AppendLine("    THROW 50400, N'AdminApiKey is not a broker API key. Create one with: dotnet run --project src/MessageBroker.Api -- new-api-key', 1;")
            .AppendLine("ELSE")
            .AppendLine("BEGIN")
            .AppendLine("    DECLARE @AppId uniqueidentifier = NEWID(), @KeyId uniqueidentifier = NEWID();")
            .AppendLine("    DECLARE @Prefix varchar(32) = LEFT(@Key, 16), @Hash varbinary(32) = HASHBYTES('SHA2_256', @Key);")
            .AppendLine("    EXEC broker.usp_Application_EnsureBootstrapAdmin @AppId, @AdminName, @KeyId, @Prefix, @Hash;")
            .AppendLine("    PRINT N'Admin application ' + @AdminName + N' has key ' + @Prefix;")
            .AppendLine("END")
            .AppendLine()
            // Lower-cased like AdminService.NormalizeHost: a bare DNS name or IP address.
            .AppendLine("DECLARE @Hosts broker.HostList;")
            .AppendLine("INSERT @Hosts (Host)")
            .AppendLine("SELECT DISTINCT LOWER(LTRIM(RTRIM(value))) FROM STRING_SPLIT(N'$(WebhookAllowedHosts)', N',')")
            .AppendLine("WHERE LTRIM(RTRIM(value)) <> N'';")
            .AppendLine("IF EXISTS (SELECT 1 FROM @Hosts WHERE Host LIKE N'%[/ ]%' OR Host LIKE N'%://%')")
            .AppendLine("    THROW 50400, N'WebhookAllowedHosts takes host names or IP addresses without scheme, port or path.', 1;")
            .AppendLine("EXEC broker.usp_AllowedHost_Seed @Hosts;")
            .AppendLine()
            .AppendLine("COMMIT TRANSACTION;")
            .AppendLine("GO")
            .ToString()
            // The file is committed (db/BrokerDb_Full.sql), so it must come out the same on every OS.
            .ReplaceLineEndings("\n");
    }

    private static StringBuilder AppendSchema(StringBuilder sql)
    {
        sql
           // sqlcmd starts with QUOTED_IDENTIFIER OFF, which filtered indexes reject; procedures also
           // keep the QUOTED_IDENTIFIER and ANSI_NULLS settings they were created with.
           .AppendLine("SET QUOTED_IDENTIFIER ON;")
           .AppendLine("SET ANSI_NULLS ON;")
           .AppendLine("SET ANSI_PADDING ON;")
           .AppendLine("SET ANSI_WARNINGS ON;")
           .AppendLine("SET ARITHABORT ON;")
           .AppendLine("SET CONCAT_NULL_YIELDS_NULL ON;")
           .AppendLine("SET NUMERIC_ROUNDABORT OFF;")
           .AppendLine("SET XACT_ABORT ON;")
           .AppendLine("SET NOEXEC OFF;")
           .AppendLine("GO")
           .AppendLine("IF SCHEMA_ID(N'broker') IS NULL EXEC(N'CREATE SCHEMA broker AUTHORIZATION dbo');")
           .AppendLine("GO")
           // The same table DbUp creates for its journal.
           .AppendLine("IF OBJECT_ID(N'broker.SchemaVersions', N'U') IS NULL")
           .AppendLine("    CREATE TABLE broker.SchemaVersions (")
           .AppendLine("        Id int IDENTITY(1,1) NOT NULL CONSTRAINT PK_SchemaVersions_Id PRIMARY KEY,")
           .AppendLine("        ScriptName nvarchar(255) NOT NULL,")
           .AppendLine("        Applied datetime NOT NULL);")
           .AppendLine("GO");

        foreach (var (name, script) in SchemaDeployer.ReadAllScripts())
        {
            sql.AppendLine().AppendLine($"-- ===== {name}");
            if (SchemaDeployer.IsMigration(name))
            {
                // NOEXEC spans batches, so it skips every GO-separated batch of an applied migration.
                var literal = name.Replace("'", "''", StringComparison.Ordinal);
                sql.AppendLine($"IF EXISTS (SELECT 1 FROM broker.SchemaVersions WHERE ScriptName = N'{literal}') SET NOEXEC ON;")
                   .AppendLine("GO")
                   .AppendLine("BEGIN TRANSACTION;")
                   .AppendLine("GO")
                   .AppendLine(script.TrimEnd())
                   .AppendLine("GO")
                   .AppendLine($"INSERT broker.SchemaVersions (ScriptName, Applied) VALUES (N'{literal}', GETDATE());")
                   .AppendLine("COMMIT TRANSACTION;")
                   .AppendLine("GO")
                   .AppendLine("SET NOEXEC OFF;")
                   .AppendLine("GO");
            }
            else
            {
                sql.AppendLine(script.TrimEnd()).AppendLine("GO");
            }
        }
        return sql;
    }
}
