<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\MessageBroker.Domain\MessageBroker.Domain.csproj" />
    <ProjectReference Include="..\..\src\MessageBroker.Application\MessageBroker.Application.csproj" />
    <ProjectReference Include="..\..\src\MessageBroker.Infrastructure\MessageBroker.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\MessageBroker.Worker\MessageBroker.Worker.csproj" />
    <ProjectReference Include="..\..\src\MessageBroker.Contracts\MessageBroker.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
