<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MessageBroker.Contracts\MessageBroker.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="MessageBroker.Dashboard.Tests" />
  </ItemGroup>
</Project>
