-- Internal Message Broker full install: database, schema and bootstrap data. Generated by
-- db/build-release-script.ps1 -Full; do not edit.
--
-- From PowerShell, use the wrapper, which passes the values for you:
--   ./db/install-database.ps1 -Server <server> -AdminApiKey <key> -WebhookAllowedHosts hooks.example.com
-- From cmd, run sqlcmd -b connected to any database on the server, passing every variable ("" for none):
--   sqlcmd -b -S <server> -i db\BrokerDb_Full.sql -v DatabaseName="BrokerDb" AdminName="broker-admin"
--          AdminApiKey="<key>" WebhookAllowedHosts="hooks.example.com,10.0.0.5"
--
--   DatabaseName         created when missing.
--   AdminName            the Admin application; empty means broker-admin.
--   AdminApiKey          its first key, from: dotnet run --project src/MessageBroker.Api -- new-api-key
--                        Only the SHA-256 hash is stored. Empty adds no key.
--   WebhookAllowedHosts  comma-separated hosts webhooks may call; empty adds none.
--
-- In SSMS, switch on Query > SQLCMD Mode and add a :setvar line for each variable at the top.
SET QUOTED_IDENTIFIER ON;
GO
DECLARE @Variables nvarchar(max) = N'$(DatabaseName)$(AdminName)$(AdminApiKey)$(WebhookAllowedHosts)';
IF LTRIM(RTRIM(N'$(DatabaseName)')) = N'' THROW 50400, N'DatabaseName is required.', 1;
GO
IF DB_ID(N'$(DatabaseName)') IS NULL
BEGIN
    PRINT N'Creating database $(DatabaseName)';
    CREATE DATABASE [$(DatabaseName)];
END
GO
USE [$(DatabaseName)];
GO

SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
SET XACT_ABORT ON;
SET NOEXEC OFF;
GO
IF SCHEMA_ID(N'broker') IS NULL EXEC(N'CREATE SCHEMA broker AUTHORIZATION dbo');
GO
IF OBJECT_ID(N'broker.SchemaVersions', N'U') IS NULL
    CREATE TABLE broker.SchemaVersions (
        Id int IDENTITY(1,1) NOT NULL CONSTRAINT PK_SchemaVersions_Id PRIMARY KEY,
        ScriptName nvarchar(255) NOT NULL,
        Applied datetime NOT NULL);
GO

-- ===== MessageBroker.Infrastructure.db.Migrations.0001_Schema.sql
IF EXISTS (SELECT 1 FROM broker.SchemaVersions WHERE ScriptName = N'MessageBroker.Infrastructure.db.Migrations.0001_Schema.sql') SET NOEXEC ON;
GO
BEGIN TRANSACTION;
GO
-- Internal Message Broker, Phase 1 schema.
-- Runs once (journaled by DbUp). Procedures, views and functions live in db/Programmability and are
-- re-applied on every deploy. Targets SQL Server 2019+, so no native json type, LEAST/GREATEST or
-- GENERATE_SERIES.

IF SCHEMA_ID(N'broker') IS NULL EXEC(N'CREATE SCHEMA broker AUTHORIZATION dbo');
GO

CREATE TABLE broker.Applications
(
    AppId      uniqueidentifier NOT NULL CONSTRAINT PK_Applications PRIMARY KEY,
    Name       nvarchar(100) COLLATE Latin1_General_100_CI_AS NOT NULL CONSTRAINT UQ_Applications_Name UNIQUE,
    IsAdmin    bit           NOT NULL CONSTRAINT DF_Applications_IsAdmin DEFAULT (0),
    IsActive   bit           NOT NULL CONSTRAINT DF_Applications_IsActive DEFAULT (1),
    CreatedAt  datetime2(3)  NOT NULL CONSTRAINT DF_Applications_CreatedAt DEFAULT (SYSUTCDATETIME())
);
GO

-- [Fix 6] Keys live in their own table so an application can hold two active keys during rotation.
CREATE TABLE broker.ApiKeys
(
    KeyId      uniqueidentifier NOT NULL CONSTRAINT PK_ApiKeys PRIMARY KEY,
    AppId      uniqueidentifier NOT NULL CONSTRAINT FK_ApiKeys_Applications REFERENCES broker.Applications (AppId),
    Prefix     varchar(32)   NOT NULL CONSTRAINT UQ_ApiKeys_Prefix UNIQUE,
    Hash       varbinary(32) NOT NULL,
    IsActive   bit           NOT NULL CONSTRAINT DF_ApiKeys_IsActive DEFAULT (1),
    CreatedAt  datetime2(3)  NOT NULL CONSTRAINT DF_ApiKeys_CreatedAt DEFAULT (SYSUTCDATETIME()),
    ExpiresAt  datetime2(3)  NULL
);
CREATE INDEX IX_ApiKeys_AppId ON broker.ApiKeys (AppId) WHERE IsActive = 1;
GO

CREATE TABLE broker.AppPermissions
(
    AppId        uniqueidentifier NOT NULL CONSTRAINT FK_AppPermissions_Applications REFERENCES broker.Applications (AppId),
    ResourceType varchar(20)  NOT NULL CONSTRAINT CK_AppPermissions_ResourceType CHECK (ResourceType IN ('Topic', 'Subscription')),
    ResourceId   uniqueidentifier NOT NULL,
    Permission   varchar(20)  NOT NULL CONSTRAINT CK_AppPermissions_Permission CHECK (Permission IN ('Publish', 'Receive', 'Manage')),
    CONSTRAINT PK_AppPermissions PRIMARY KEY (AppId, ResourceType, ResourceId, Permission)
);
GO

CREATE TABLE broker.Topics
(
    TopicId           uniqueidentifier NOT NULL CONSTRAINT PK_Topics PRIMARY KEY,
    Name              nvarchar(100) COLLATE Latin1_General_100_CI_AS NOT NULL,
    DefaultTtlSeconds int          NULL CONSTRAINT CK_Topics_DefaultTtl CHECK (DefaultTtlSeconds > 0),
    IsDeleted         bit          NOT NULL CONSTRAINT DF_Topics_IsDeleted DEFAULT (0),
    CreatedAt         datetime2(3) NOT NULL CONSTRAINT DF_Topics_CreatedAt DEFAULT (SYSUTCDATETIME())
);
CREATE UNIQUE INDEX UQ_Topics_Name ON broker.Topics (Name) WHERE IsDeleted = 0;
GO

CREATE TABLE broker.Subscriptions
(
    SubscriptionId          uniqueidentifier NOT NULL CONSTRAINT PK_Subscriptions PRIMARY KEY,
    TopicId                 uniqueidentifier NOT NULL CONSTRAINT FK_Subscriptions_Topics REFERENCES broker.Topics (TopicId),
    Name                    nvarchar(100) COLLATE Latin1_General_100_CI_AS NOT NULL,
    OwnerAppId              uniqueidentifier NOT NULL CONSTRAINT FK_Subscriptions_Applications REFERENCES broker.Applications (AppId),
    Status                  varchar(10)   NOT NULL CONSTRAINT CK_Subscriptions_Status CHECK (Status IN ('Active', 'Paused', 'Deleted')),
    DeliveryMode            varchar(10)   NOT NULL CONSTRAINT CK_Subscriptions_Mode CHECK (DeliveryMode IN ('Webhook', 'SignalR', 'Pull')),
    WebhookUrl              nvarchar(2000) NULL,
    WebhookSecret           nvarchar(1000) NULL,          -- protected with ASP.NET Core Data Protection
    PreviousWebhookSecret   nvarchar(1000) NULL,          -- [Fix 7] valid until PreviousSecretExpiresAt
    PreviousSecretExpiresAt datetime2(3)  NULL,
    WebhookTimeoutSeconds   int NOT NULL,
    MaxConcurrentDeliveries int NOT NULL,
    MaxAttempts             int NOT NULL CONSTRAINT CK_Subscriptions_MaxAttempts CHECK (MaxAttempts >= 1),
    LockDurationSeconds     int NOT NULL CONSTRAINT CK_Subscriptions_Lock CHECK (LockDurationSeconds BETWEEN 1 AND 600),
    RetryBaseDelaySeconds   int NOT NULL,
    RetryMaxDelaySeconds    int NOT NULL,
    TtlSeconds              int NULL,
    CreatedAt               datetime2(3) NOT NULL CONSTRAINT DF_Subscriptions_CreatedAt DEFAULT (SYSUTCDATETIME()),
    UpdatedAt               datetime2(3) NOT NULL CONSTRAINT DF_Subscriptions_UpdatedAt DEFAULT (SYSUTCDATETIME()),
    CONSTRAINT CK_Subscriptions_Retry CHECK (RetryBaseDelaySeconds >= 1 AND RetryMaxDelaySeconds >= RetryBaseDelaySeconds)
);
CREATE UNIQUE INDEX UQ_Subscriptions_TopicName ON broker.Subscriptions (TopicId, Name) WHERE Status <> 'Deleted';
GO

CREATE TABLE broker.Messages
(
    MessageSeq     bigint IDENTITY (1, 1) NOT NULL CONSTRAINT PK_Messages PRIMARY KEY CLUSTERED,
    MessageId      uniqueidentifier NOT NULL CONSTRAINT UQ_Messages_MessageId UNIQUE NONCLUSTERED,
    TopicId        uniqueidentifier NOT NULL CONSTRAINT FK_Messages_Topics REFERENCES broker.Topics (TopicId),
    MessageType    nvarchar(200) NOT NULL,
    CorrelationId  nvarchar(100) NOT NULL,
    PublisherAppId uniqueidentifier NOT NULL CONSTRAINT FK_Messages_Applications REFERENCES broker.Applications (AppId),
    IdempotencyKey nvarchar(100) NULL,
    Payload        nvarchar(max) NOT NULL CONSTRAINT CK_Messages_PayloadJson CHECK (ISJSON(Payload) = 1),       -- [Fix 5]
    Properties     nvarchar(max) NULL CONSTRAINT CK_Messages_PropertiesJson CHECK (Properties IS NULL OR ISJSON(Properties) = 1),
    CreatedAt      datetime2(3) NOT NULL,
    ExpiresAt      datetime2(3) NULL
);
CREATE INDEX IX_Messages_CorrelationId ON broker.Messages (CorrelationId);
CREATE INDEX IX_Messages_CreatedAt ON broker.Messages (CreatedAt);
CREATE UNIQUE INDEX UQ_Messages_Idempotency ON broker.Messages (TopicId, PublisherAppId, IdempotencyKey) WHERE IdempotencyKey IS NOT NULL;
GO

-- The queue. Status: 0 Pending, 1 Leased, 2 Completed, 3 DeadLettered, 4 Cancelled.
CREATE TABLE broker.Deliveries
(
    DeliveryId        bigint IDENTITY (1, 1) NOT NULL CONSTRAINT PK_Deliveries PRIMARY KEY CLUSTERED,
    MessageId         uniqueidentifier NOT NULL CONSTRAINT FK_Deliveries_Messages REFERENCES broker.Messages (MessageId),
    SubscriptionId    uniqueidentifier NOT NULL CONSTRAINT FK_Deliveries_Subscriptions REFERENCES broker.Subscriptions (SubscriptionId),
    Status            tinyint NOT NULL CONSTRAINT CK_Deliveries_Status CHECK (Status BETWEEN 0 AND 4),
    AttemptCount      int NOT NULL CONSTRAINT DF_Deliveries_AttemptCount DEFAULT (0),      -- reset by requeue; compared to MaxAttempts
    TotalAttemptCount int NOT NULL CONSTRAINT DF_Deliveries_TotalAttemptCount DEFAULT (0), -- [Fix 1] never reset; numbers attempts
    AvailableAt       datetime2(3) NOT NULL,
    LockedUntil       datetime2(3) NULL,
    LockToken         uniqueidentifier NULL,
    ExpiresAt         datetime2(3) NULL,
    CreatedAt         datetime2(3) NOT NULL,
    CompletedAt       datetime2(3) NULL,
    CONSTRAINT UQ_Deliveries_MessageSubscription UNIQUE (MessageId, SubscriptionId)
);
CREATE INDEX IX_Deliveries_Lease ON broker.Deliveries (SubscriptionId, Status, AvailableAt) INCLUDE (ExpiresAt);
CREATE INDEX IX_Deliveries_LockedUntil ON broker.Deliveries (LockedUntil) WHERE Status = 1;
CREATE INDEX IX_Deliveries_ExpiresAt ON broker.Deliveries (ExpiresAt) WHERE Status = 0 AND ExpiresAt IS NOT NULL;
CREATE INDEX IX_Deliveries_CompletedAt ON broker.Deliveries (CompletedAt) WHERE Status IN (2, 4);
GO

CREATE TABLE broker.DeliveryAttempts
(
    AttemptId      bigint IDENTITY (1, 1) NOT NULL CONSTRAINT PK_DeliveryAttempts PRIMARY KEY CLUSTERED,
    DeliveryId     bigint NOT NULL CONSTRAINT FK_DeliveryAttempts_Deliveries REFERENCES broker.Deliveries (DeliveryId),
    AttemptNumber  int NOT NULL,
    Channel        varchar(10) NOT NULL CONSTRAINT CK_DeliveryAttempts_Channel CHECK (Channel IN ('Webhook', 'SignalR', 'Pull')),
    LeasedAt       datetime2(3) NOT NULL,
    EndedAt        datetime2(3) NULL,
    Outcome        varchar(20) NULL CONSTRAINT CK_DeliveryAttempts_Outcome CHECK (Outcome IN ('Acked', 'Nacked', 'LeaseExpired', 'Cancelled')),
    HttpStatusCode int NULL,
    DurationMs     int NULL,
    ErrorCode      nvarchar(100) NULL,
    ErrorMessage   nvarchar(1000) NULL,
    ErrorDetail    nvarchar(max) NULL,
    CONSTRAINT UQ_DeliveryAttempts_Number UNIQUE (DeliveryId, AttemptNumber)
);
GO

-- [Fix 1] One row per dead-lettering, so a requeued delivery can be dead-lettered again.
CREATE TABLE broker.DeadLetters
(
    DeadLetterId   bigint IDENTITY (1, 1) NOT NULL CONSTRAINT PK_DeadLetters PRIMARY KEY CLUSTERED,
    DeliveryId     bigint NOT NULL CONSTRAINT FK_DeadLetters_Deliveries REFERENCES broker.Deliveries (DeliveryId),
    MessageId      uniqueidentifier NOT NULL,
    SubscriptionId uniqueidentifier NOT NULL,
    TopicId        uniqueidentifier NOT NULL,
    Reason         varchar(30) NOT NULL CONSTRAINT CK_DeadLetters_Reason CHECK (Reason IN ('MaxAttemptsExceeded', 'Expired', 'RejectedBySubscriber')),
    AttemptCount   int NOT NULL,
    LastError      nvarchar(1000) NULL,
    FirstFailureAt datetime2(3) NULL,
    LastFailureAt  datetime2(3) NULL,
    DeadLetteredAt datetime2(3) NOT NULL,
    RequeuedAt     datetime2(3) NULL,
    RequeuedBy     uniqueidentifier NULL
);
CREATE UNIQUE INDEX UQ_DeadLetters_OpenDelivery ON broker.DeadLetters (DeliveryId) WHERE RequeuedAt IS NULL;
CREATE INDEX IX_DeadLetters_Subscription ON broker.DeadLetters (SubscriptionId, DeadLetteredAt DESC);
GO

-- [Fix 8] Dispatcher heartbeat, read by /health/ready.
CREATE TABLE broker.BrokerHeartbeats
(
    InstanceId nvarchar(200) NOT NULL CONSTRAINT PK_BrokerHeartbeats PRIMARY KEY,
    LastBeatAt datetime2(3)  NOT NULL
);
GO

-- [Fix 9] Webhook host allowlist, maintained by Admins; configuration only seeds it.
CREATE TABLE broker.WebhookAllowedHosts
(
    Host    nvarchar(255) COLLATE Latin1_General_100_CI_AS NOT NULL CONSTRAINT PK_WebhookAllowedHosts PRIMARY KEY,
    AddedBy uniqueidentifier NULL,
    AddedAt datetime2(3) NOT NULL CONSTRAINT DF_WebhookAllowedHosts_AddedAt DEFAULT (SYSUTCDATETIME())
);
GO

CREATE TYPE broker.HostList AS TABLE (Host nvarchar(255) COLLATE Latin1_General_100_CI_AS NOT NULL PRIMARY KEY);
GO
GO
INSERT broker.SchemaVersions (ScriptName, Applied) VALUES (N'MessageBroker.Infrastructure.db.Migrations.0001_Schema.sql', GETDATE());
COMMIT TRANSACTION;
GO
SET NOEXEC OFF;
GO

-- ===== MessageBroker.Infrastructure.db.Migrations.0002_SettleSeekIndexes.sql
IF EXISTS (SELECT 1 FROM broker.SchemaVersions WHERE ScriptName = N'MessageBroker.Infrastructure.db.Migrations.0002_SettleSeekIndexes.sql') SET NOEXEC ON;
GO
BEGIN TRANSACTION;
GO
-- Settlement reads a delivery's dead-letter history (the last requeue). Without this index that read
-- scans DeadLetters, and two concurrent settles of different deliveries can deadlock on each other's
-- rows. The settle procedures seek it with FORCESEEK, as they do UQ_DeliveryAttempts_Number.
CREATE INDEX IX_DeadLetters_Delivery ON broker.DeadLetters (DeliveryId) INCLUDE (RequeuedAt);
GO
GO
INSERT broker.SchemaVersions (ScriptName, Applied) VALUES (N'MessageBroker.Infrastructure.db.Migrations.0002_SettleSeekIndexes.sql', GETDATE());
COMMIT TRANSACTION;
GO
SET NOEXEC OFF;
GO

-- ===== MessageBroker.Infrastructure.db.Migrations.0003_DashboardIndexes.sql
IF EXISTS (SELECT 1 FROM broker.SchemaVersions WHERE ScriptName = N'MessageBroker.Infrastructure.db.Migrations.0003_DashboardIndexes.sql') SET NOEXEC ON;
GO
BEGIN TRANSACTION;
GO
-- Indexes for the admin dashboard's queries (Dashboard.sql): topic-filtered message paging and the
-- per-minute throughput series. Deliveries by MessageId already seek UQ_Deliveries_MessageSubscription.

CREATE INDEX IX_Messages_Topic ON broker.Messages (TopicId, MessageSeq DESC);
CREATE INDEX IX_DeadLetters_DeadLetteredAt ON broker.DeadLetters (DeadLetteredAt) INCLUDE (SubscriptionId, Reason, RequeuedAt);
CREATE INDEX IX_DeliveryAttempts_EndedAt ON broker.DeliveryAttempts (EndedAt) INCLUDE (Outcome) WHERE EndedAt IS NOT NULL;
GO
GO
INSERT broker.SchemaVersions (ScriptName, Applied) VALUES (N'MessageBroker.Infrastructure.db.Migrations.0003_DashboardIndexes.sql', GETDATE());
COMMIT TRANSACTION;
GO
SET NOEXEC OFF;
GO

-- ===== MessageBroker.Infrastructure.db.Programmability.Functions.fn_HasPermission.sql
-- Returns one row with Allowed = 1 when the application is an active admin, or holds the permission
-- (or Manage) on the resource. Used by every procedure that acts on behalf of a caller.
CREATE OR ALTER FUNCTION broker.fn_HasPermission
(
    @AppId        uniqueidentifier,
    @ResourceType varchar(20),
    @ResourceId   uniqueidentifier,
    @Permission   varchar(20)
)
RETURNS TABLE
AS
RETURN
    SELECT CAST(CASE
        WHEN EXISTS (SELECT 1 FROM broker.Applications a
                     WHERE a.AppId = @AppId AND a.IsActive = 1 AND a.IsAdmin = 1) THEN 1
        WHEN EXISTS (SELECT 1 FROM broker.AppPermissions p
                     JOIN broker.Applications a ON a.AppId = p.AppId AND a.IsActive = 1
                     WHERE p.AppId = @AppId
                       AND p.ResourceType = @ResourceType
                       AND p.ResourceId = @ResourceId
                       AND p.Permission IN (@Permission, 'Manage')) THEN 1
        ELSE 0 END AS bit) AS Allowed;
GO
GO

-- ===== MessageBroker.Infrastructure.db.Programmability.Views.Views.sql
-- [Fix 12] Derived message status. Cancelled deliveries are ignored: a deleted subscription says
-- nothing about whether the message was processed. A message with no deliveries is Completed.
CREATE OR ALTER VIEW broker.vw_MessageStatus
AS
SELECT
    m.MessageId,
    CASE
        WHEN SUM(CASE WHEN d.Status IN (0, 1) THEN 1 ELSE 0 END) > 0 THEN 'InProgress'
        WHEN SUM(CASE WHEN d.Status = 3 THEN 1 ELSE 0 END) = 0 THEN 'Completed'
        WHEN SUM(CASE WHEN d.Status = 3 THEN 1 ELSE 0 END) = SUM(CASE WHEN d.Status <> 4 THEN 1 ELSE 0 END) THEN 'DeadLettered'
        ELSE 'PartiallyDeadLettered'
    END AS Status,
    COUNT(d.DeliveryId) AS DeliveryCount,
    SUM(CASE WHEN d.Status = 0 THEN 1 ELSE 0 END) AS PendingCount,
    SUM(CASE WHEN d.Status = 1 THEN 1 ELSE 0 END) AS LeasedCount,
    SUM(CASE WHEN d.Status = 2 THEN 1 ELSE 0 END) AS CompletedCount,
    SUM(CASE WHEN d.Status = 3 THEN 1 ELSE 0 END) AS DeadLetteredCount,
    SUM(CASE WHEN d.Status = 4 THEN 1 ELSE 0 END) AS CancelledCount
FROM broker.Messages m
LEFT JOIN broker.Deliveries d ON d.MessageId = m.MessageId
GROUP BY m.MessageId;
GO

-- Backlog and DLQ size per subscription (spec section 13, operational queries).
CREATE OR ALTER VIEW broker.vw_SubscriptionDeliveryCounts
AS
SELECT
    s.SubscriptionId,
    SUM(CASE WHEN d.Status = 0 THEN 1 ELSE 0 END) AS PendingCount,
    SUM(CASE WHEN d.Status = 1 THEN 1 ELSE 0 END) AS LeasedCount,
    SUM(CASE WHEN d.Status = 3 THEN 1 ELSE 0 END) AS DeadLetteredCount
FROM broker.Subscriptions s
LEFT JOIN broker.Deliveries d ON d.SubscriptionId = s.SubscriptionId AND d.Status IN (0, 1, 3)
GROUP BY s.SubscriptionId;
GO

-- Subscription with its topic name and delivery counts; the shape returned by the subscription procedures.
CREATE OR ALTER VIEW broker.vw_SubscriptionDetails
AS
SELECT
    s.SubscriptionId,
    s.TopicId,
    t.Name AS TopicName,
    s.Name,
    s.OwnerAppId,
    s.Status,
    s.DeliveryMode,
    s.WebhookUrl,
    s.WebhookSecret,
    s.PreviousWebhookSecret,
    s.PreviousSecretExpiresAt,
    s.WebhookTimeoutSeconds,
    s.MaxConcurrentDeliveries,
    s.MaxAttempts,
    s.LockDurationSeconds,
    s.RetryBaseDelaySeconds,
    s.RetryMaxDelaySeconds,
    s.TtlSeconds,
    s.CreatedAt,
    s.UpdatedAt,
    c.PendingCount,
    c.LeasedCount,
    c.DeadLetteredCount
FROM broker.Subscriptions s
JOIN broker.Topics t ON t.TopicId = s.TopicId
JOIN broker.vw_SubscriptionDeliveryCounts c ON c.SubscriptionId = s.SubscriptionId;
GO

-- A DLQ entry with the message and names an operator needs, without copying the payload.
CREATE OR ALTER VIEW broker.vw_DeadLetterDetails
AS
SELECT
    dl.DeadLetterId,
    dl.DeliveryId,
    dl.MessageId,
    dl.SubscriptionId,
    s.Name AS SubscriptionName,
    dl.TopicId,
    t.Name AS TopicName,
    dl.Reason,
    dl.AttemptCount,
    dl.LastError,
    dl.FirstFailureAt,
    dl.LastFailureAt,
    dl.DeadLetteredAt,
    dl.RequeuedAt,
    dl.RequeuedBy,
    m.MessageType,
    m.CorrelationId,
    m.CreatedAt AS MessageCreatedAt,
    m.Properties,
    m.Payload
FROM broker.DeadLetters dl
JOIN broker.Messages m ON m.MessageId = dl.MessageId
JOIN broker.Subscriptions s ON s.SubscriptionId = dl.SubscriptionId
JOIN broker.Topics t ON t.TopicId = dl.TopicId;
GO

-- Push subscriptions the lease loop works on. HasDueDeliveries lets it skip idle subscriptions cheaply.
CREATE OR ALTER VIEW broker.vw_ActivePushSubscriptions
AS
SELECT
    s.SubscriptionId,
    s.TopicId,
    s.Name,
    s.DeliveryMode,
    s.WebhookUrl,
    s.WebhookSecret,
    s.PreviousWebhookSecret,
    s.PreviousSecretExpiresAt,
    s.WebhookTimeoutSeconds,
    s.MaxConcurrentDeliveries,
    s.LockDurationSeconds,
    -- Compared with the clock at millisecond precision, as usp_Delivery_Lease does: a stored
    -- datetime2(3) can be rounded up, and against the raw clock a delivery published within the last
    -- half millisecond would look not yet due, so the lease loop would skip it until its next pass.
    CAST(CASE WHEN EXISTS (
        SELECT 1 FROM broker.Deliveries d
        WHERE d.SubscriptionId = s.SubscriptionId
          AND d.Status = 0
          AND d.AvailableAt <= CAST(SYSUTCDATETIME() AS datetime2(3))
          AND (d.ExpiresAt IS NULL OR d.ExpiresAt > CAST(SYSUTCDATETIME() AS datetime2(3)))) THEN 1 ELSE 0 END AS bit) AS HasDueDeliveries
FROM broker.Subscriptions s
WHERE s.Status = 'Active'
  AND s.DeliveryMode IN ('Webhook', 'SignalR');
GO
GO

-- ===== MessageBroker.Infrastructure.db.Programmability.Procedures.Auth.sql
-- Applications, API keys and permissions.
-- Error numbers: 50400 validation, 50403 forbidden, 50404 not found, 50409 conflict, 50410 lease lost.

CREATE OR ALTER PROCEDURE broker.usp_Application_Create
    @AppId   uniqueidentifier,
    @Name    nvarchar(100),
    @IsAdmin bit
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    IF EXISTS (SELECT 1 FROM broker.Applications WHERE Name = @Name)
        THROW 50409, N'An application with this name already exists.', 1;

    INSERT broker.Applications (AppId, Name, IsAdmin) VALUES (@AppId, @Name, @IsAdmin);

    SELECT AppId, Name, IsAdmin, IsActive, CreatedAt FROM broker.Applications WHERE AppId = @AppId;
END
GO

CREATE OR ALTER PROCEDURE broker.usp_Application_Get
    @AppId uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;
    SELECT AppId, Name, IsAdmin, IsActive, CreatedAt FROM broker.Applications WHERE AppId = @AppId;
END
GO

CREATE OR ALTER PROCEDURE broker.usp_Application_List
AS
BEGIN
    SET NOCOUNT ON;
    SELECT AppId, Name, IsAdmin, IsActive, CreatedAt FROM broker.Applications ORDER BY Name;
END
GO

CREATE OR ALTER PROCEDURE broker.usp_Application_SetActive
    @AppId    uniqueidentifier,
    @IsActive bit
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    UPDATE broker.Applications SET IsActive = @IsActive WHERE AppId = @AppId;
    IF @@ROWCOUNT = 0
        THROW 50404, N'Application was not found.', 1;
END
GO

-- [Fix 6] At most two active, unexpired keys per application, so keys can be rotated without downtime.
CREATE OR ALTER PROCEDURE broker.usp_ApiKey_Create
    @KeyId     uniqueidentifier,
    @AppId     uniqueidentifier,
    @Prefix    varchar(32),
    @Hash      varbinary(32),
    @ExpiresAt datetime2(3) = NULL
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    BEGIN TRAN;

    IF NOT EXISTS (SELECT 1 FROM broker.Applications WITH (UPDLOCK, HOLDLOCK) WHERE AppId = @AppId)
    BEGIN
        ROLLBACK;
        THROW 50404, N'Application was not found.', 1;
    END

    IF (SELECT COUNT(*) FROM broker.ApiKeys
        WHERE AppId = @AppId AND IsActive = 1 AND (ExpiresAt IS NULL OR ExpiresAt > SYSUTCDATETIME())) >= 2
    BEGIN
        ROLLBACK;
        THROW 50409, N'The application already has two active keys. Deactivate one before issuing another.', 1;
    END

    INSERT broker.ApiKeys (KeyId, AppId, Prefix, Hash, ExpiresAt) VALUES (@KeyId, @AppId, @Prefix, @Hash, @ExpiresAt);

    COMMIT;

    SELECT KeyId, AppId, Prefix, IsActive, CreatedAt, ExpiresAt FROM broker.ApiKeys WHERE KeyId = @KeyId;
END
GO

CREATE OR ALTER PROCEDURE broker.usp_ApiKey_Deactivate
    @AppId uniqueidentifier,
    @KeyId uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    UPDATE broker.ApiKeys SET IsActive = 0 WHERE KeyId = @KeyId AND AppId = @AppId;
    IF @@ROWCOUNT = 0
        THROW 50404, N'API key was not found.', 1;
END
GO

CREATE OR ALTER PROCEDURE broker.usp_ApiKey_List
    @AppId uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;
    SELECT KeyId, AppId, Prefix, IsActive, CreatedAt, ExpiresAt
    FROM broker.ApiKeys WHERE AppId = @AppId ORDER BY CreatedAt;
END
GO

-- Authentication lookup. Only keys that are active, unexpired and belong to an active application resolve.
CREATE OR ALTER PROCEDURE broker.usp_ApiKey_GetByPrefix
    @Prefix varchar(32)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT k.KeyId, k.AppId, k.Hash, a.Name AS AppName, a.IsAdmin
    FROM broker.ApiKeys k
    JOIN broker.Applications a ON a.AppId = k.AppId
    WHERE k.Prefix = @Prefix
      AND k.IsActive = 1
      AND a.IsActive = 1
      AND (k.ExpiresAt IS NULL OR k.ExpiresAt > SYSUTCDATETIME());
END
GO

-- Creates the first admin application and key from configuration. Safe to run on every start.
CREATE OR ALTER PROCEDURE broker.usp_Application_EnsureBootstrapAdmin
    @AppId  uniqueidentifier,
    @Name   nvarchar(100),
    @KeyId  uniqueidentifier,
    @Prefix varchar(32),
    @Hash   varbinary(32)
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    BEGIN TRAN;

    IF NOT EXISTS (SELECT 1 FROM broker.ApiKeys WITH (UPDLOCK, HOLDLOCK) WHERE Prefix = @Prefix)
    BEGIN
        DECLARE @ExistingAppId uniqueidentifier = (SELECT AppId FROM broker.Applications WHERE Name = @Name);
        IF @ExistingAppId IS NULL
            INSERT broker.Applications (AppId, Name, IsAdmin) VALUES (@AppId, @Name, 1);
        ELSE
            SET @AppId = @ExistingAppId;

        INSERT broker.ApiKeys (KeyId, AppId, Prefix, Hash) VALUES (@KeyId, @AppId, @Prefix, @Hash);
    END

    COMMIT;
END
GO

CREATE OR ALTER PROCEDURE broker.usp_Permission_Grant
    @AppId        uniqueidentifier,
    @ResourceType varchar(20),
    @ResourceId   uniqueidentifier,
    @Permission   varchar(20)
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    IF NOT EXISTS (SELECT 1 FROM broker.Applications WHERE AppId = @AppId)
        THROW 50404, N'Application was not found.', 1;

    IF (@ResourceType = 'Topic' AND NOT EXISTS (SELECT 1 FROM broker.Topics WHERE TopicId = @ResourceId AND IsDeleted = 0))
       OR (@ResourceType = 'Subscription' AND NOT EXISTS (SELECT 1 FROM broker.Subscriptions WHERE SubscriptionId = @ResourceId AND Status <> 'Deleted'))
        THROW 50404, N'The resource was not found.', 1;

    IF NOT EXISTS (SELECT 1 FROM broker.AppPermissions
                   WHERE AppId = @AppId AND ResourceType = @ResourceType AND ResourceId = @ResourceId AND Permission = @Permission)
        INSERT broker.AppPermissions (AppId, ResourceType, ResourceId, Permission)
        VALUES (@AppId, @ResourceType, @ResourceId, @Permission);
END
GO

CREATE OR ALTER PROCEDURE broker.usp_Permission_Revoke
    @AppId        uniqueidentifier,
    @ResourceType varchar(20),
    @ResourceId   uniqueidentifier,
    @Permission   varchar(20)
AS
BEGIN
    SET NOCOUNT ON;
    DELETE broker.AppPermissions
    WHERE AppId = @AppId AND ResourceType = @ResourceType AND ResourceId = @ResourceId AND Permission = @Permission;
END
GO

CREATE OR ALTER PROCEDURE broker.usp_Permission_List
    @AppId uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;
    SELECT AppId, ResourceType, ResourceId, Permission
    FROM broker.AppPermissions WHERE AppId = @AppId
    ORDER BY ResourceType, ResourceId, Permission;
END
GO

CREATE OR ALTER PROCEDURE broker.usp_Permission_Check
    @AppId        uniqueidentifier,
    @ResourceType varchar(20),
    @ResourceId   uniqueidentifier,
    @Permission   varchar(20)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT Allowed FROM broker.fn_HasPermission(@AppId, @ResourceType, @ResourceId, @Permission);
END
GO

-- [Fix 9] Webhook host allowlist.
CREATE OR ALTER PROCEDURE broker.usp_AllowedHost_Add
    @Host    nvarchar(255),
    @AddedBy uniqueidentifier = NULL
AS
BEGIN
    SET NOCOUNT ON;
    IF NOT EXISTS (SELECT 1 FROM broker.WebhookAllowedHosts WHERE Host = @Host)
        INSERT broker.WebhookAllowedHosts (Host, AddedBy) VALUES (@Host, @AddedBy);
END
GO

CREATE OR ALTER PROCEDURE broker.usp_AllowedHost_Remove
    @Host nvarchar(255)
AS
BEGIN
    SET NOCOUNT ON;
    DELETE broker.WebhookAllowedHosts WHERE Host = @Host;
    IF @@ROWCOUNT = 0
        THROW 50404, N'Host is not on the allowlist.', 1;
END
GO

CREATE OR ALTER PROCEDURE broker.usp_AllowedHost_List
AS
BEGIN
    SET NOCOUNT ON;
    SELECT Host, AddedBy, AddedAt FROM broker.WebhookAllowedHosts ORDER BY Host;
END
GO

-- Adds configured hosts that are missing. Never removes hosts an Admin added.
CREATE OR ALTER PROCEDURE broker.usp_AllowedHost_Seed
    @Hosts broker.HostList READONLY
AS
BEGIN
    SET NOCOUNT ON;
    INSERT broker.WebhookAllowedHosts (Host)
    SELECT h.Host FROM @Hosts h
    WHERE NOT EXISTS (SELECT 1 FROM broker.WebhookAllowedHosts w WHERE w.Host = h.Host);
END
GO
GO

-- ===== MessageBroker.Infrastructure.db.Programmability.Procedures.Dashboard.sql
-- Admin dashboard queries. Admin only: DashboardService checks the caller before calling these.

-- Broker-wide overview: totals, a per-minute throughput series over the last @WindowMinutes, one row
-- per subscription (never its secrets) and the dispatcher heartbeat. Four result sets.
CREATE OR ALTER PROCEDURE broker.usp_Admin_GetOverview
    @WindowMinutes int = 60
AS
BEGIN
    SET NOCOUNT ON;

    IF @WindowMinutes IS NULL OR @WindowMinutes NOT BETWEEN 5 AND 1440
        THROW 50400, N'windowMinutes must be between 5 and 1440.', 1;

    DECLARE @Now datetime2(3) = SYSUTCDATETIME();
    -- The series starts on a whole minute so every bucket is a full calendar minute except the current one.
    DECLARE @Start datetime2(3) = DATEADD(minute, DATEDIFF(minute, '2000-01-01', @Now) - (@WindowMinutes - 1), CAST('2000-01-01' AS datetime2(3)));

    SELECT
        (SELECT COUNT_BIG(*) FROM broker.Deliveries WHERE Status = 0) AS PendingCount,
        (SELECT COUNT_BIG(*) FROM broker.Deliveries WHERE Status = 1) AS LeasedCount,
        -- Only live subscriptions: a deleted one's DLQ entries can no longer be requeued.
        (SELECT COUNT_BIG(*) FROM broker.DeadLetters dl
         JOIN broker.Subscriptions s ON s.SubscriptionId = dl.SubscriptionId
         WHERE dl.RequeuedAt IS NULL AND s.Status <> 'Deleted') AS DeadLetteredCount,
        (SELECT COUNT_BIG(*) FROM broker.Messages WHERE CreatedAt >= @Start) AS PublishedInWindow,
        (SELECT COUNT_BIG(*) FROM broker.Deliveries WHERE Status = 2 AND CompletedAt >= @Start) AS CompletedInWindow,
        @WindowMinutes AS WindowMinutes,
        @Now AS GeneratedAt;

    WITH minutes AS
    (
        SELECT TOP (@WindowMinutes) ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) - 1 AS N
        FROM sys.all_objects
    ),
    published AS
    (
        SELECT DATEDIFF(minute, @Start, CreatedAt) AS N, COUNT(*) AS C
        FROM broker.Messages WHERE CreatedAt >= @Start GROUP BY DATEDIFF(minute, @Start, CreatedAt)
    ),
    completed AS
    (
        SELECT DATEDIFF(minute, @Start, CompletedAt) AS N, COUNT(*) AS C
        FROM broker.Deliveries WHERE Status = 2 AND CompletedAt >= @Start
        GROUP BY DATEDIFF(minute, @Start, CompletedAt)
    ),
    failed AS
    (
        SELECT DATEDIFF(minute, @Start, EndedAt) AS N, COUNT(*) AS C
        FROM broker.DeliveryAttempts WHERE EndedAt >= @Start AND Outcome IN ('Nacked', 'LeaseExpired')
        GROUP BY DATEDIFF(minute, @Start, EndedAt)
    ),
    deadLettered AS
    (
        SELECT DATEDIFF(minute, @Start, DeadLetteredAt) AS N, COUNT(*) AS C
        FROM broker.DeadLetters WHERE DeadLetteredAt >= @Start GROUP BY DATEDIFF(minute, @Start, DeadLetteredAt)
    )
    SELECT DATEADD(minute, m.N, @Start) AS Minute,
           COALESCE(p.C, 0) AS Published,
           COALESCE(c.C, 0) AS Completed,
           COALESCE(f.C, 0) AS Failed,
           COALESCE(d.C, 0) AS DeadLettered
    FROM minutes m
    LEFT JOIN published p ON p.N = m.N
    LEFT JOIN completed c ON c.N = m.N
    LEFT JOIN failed f ON f.N = m.N
    LEFT JOIN deadLettered d ON d.N = m.N
    ORDER BY m.N;

    SELECT s.SubscriptionId, s.Name, s.TopicId, s.TopicName, s.OwnerAppId, s.Status, s.DeliveryMode,
           s.PendingCount, s.LeasedCount, s.DeadLetteredCount
    FROM broker.vw_SubscriptionDetails s
    WHERE s.Status <> 'Deleted'
    ORDER BY s.TopicName, s.Name;

    SELECT MAX(LastBeatAt) AS LastBeatAt, @Now AS DbNow FROM broker.BrokerHeartbeats;
END
GO

-- Messages newest first, filtered, with keyset paging: pass the smallest MessageSeq of the previous
-- page as @BeforeSeq. The status is derived as in vw_MessageStatus, per message on the page.
CREATE OR ALTER PROCEDURE broker.usp_Admin_Message_Search
    @TopicId        uniqueidentifier = NULL,
    @Status         varchar(30) = NULL,
    @MessageType    nvarchar(200) = NULL,
    @CorrelationId  nvarchar(100) = NULL,
    @PublisherAppId uniqueidentifier = NULL,
    @From           datetime2(3) = NULL,
    @To             datetime2(3) = NULL,
    @BeforeSeq      bigint = NULL,
    @PageSize       int = 50
AS
BEGIN
    SET NOCOUNT ON;

    IF @PageSize IS NULL OR @PageSize NOT BETWEEN 1 AND 200
        THROW 50400, N'pageSize must be between 1 and 200.', 1;
    IF @From IS NOT NULL AND @To IS NOT NULL AND @From > @To
        THROW 50400, N'from must not be later than to.', 1;
    IF @Status IS NOT NULL AND @Status NOT IN ('InProgress', 'Completed', 'PartiallyDeadLettered', 'DeadLettered')
        THROW 50400, N'status must be InProgress, Completed, PartiallyDeadLettered or DeadLettered.', 1;

    SELECT TOP (@PageSize)
           m.MessageSeq, m.MessageId, t.Name AS TopicName, m.MessageType, m.CorrelationId, m.PublisherAppId,
           a.Name AS PublisherName, m.CreatedAt, m.ExpiresAt, st.Status, st.DeliveryCount,
           st.PendingCount, st.LeasedCount, st.CompletedCount, st.DeadLetteredCount
    FROM broker.Messages m
    JOIN broker.Topics t ON t.TopicId = m.TopicId
    JOIN broker.Applications a ON a.AppId = m.PublisherAppId
    CROSS APPLY
    (
        SELECT
            CASE
                WHEN SUM(CASE WHEN d.Status IN (0, 1) THEN 1 ELSE 0 END) > 0 THEN 'InProgress'
                WHEN COALESCE(SUM(CASE WHEN d.Status = 3 THEN 1 ELSE 0 END), 0) = 0 THEN 'Completed'
                WHEN SUM(CASE WHEN d.Status = 3 THEN 1 ELSE 0 END) = SUM(CASE WHEN d.Status <> 4 THEN 1 ELSE 0 END) THEN 'DeadLettered'
                ELSE 'PartiallyDeadLettered'
            END AS Status,
            COUNT(d.DeliveryId) AS DeliveryCount,
            COALESCE(SUM(CASE WHEN d.Status = 0 THEN 1 ELSE 0 END), 0) AS PendingCount,
            COALESCE(SUM(CASE WHEN d.Status = 1 THEN 1 ELSE 0 END), 0) AS LeasedCount,
            COALESCE(SUM(CASE WHEN d.Status = 2 THEN 1 ELSE 0 END), 0) AS CompletedCount,
            COALESCE(SUM(CASE WHEN d.Status = 3 THEN 1 ELSE 0 END), 0) AS DeadLetteredCount
        FROM broker.Deliveries d
        WHERE d.MessageId = m.MessageId
    ) st
    WHERE (@TopicId IS NULL OR m.TopicId = @TopicId)
      AND (@MessageType IS NULL OR m.MessageType = @MessageType)
      AND (@CorrelationId IS NULL OR m.CorrelationId = @CorrelationId)
      AND (@PublisherAppId IS NULL OR m.PublisherAppId = @PublisherAppId)
      AND (@From IS NULL OR m.CreatedAt >= @From)
      AND (@To IS NULL OR m.CreatedAt <= @To)
      AND (@BeforeSeq IS NULL OR m.MessageSeq < @BeforeSeq)
      AND (@Status IS NULL OR st.Status = @Status)
    ORDER BY m.MessageSeq DESC
    OPTION (RECOMPILE);
END
GO

-- Broker-wide DLQ, newest first; keyset paging on DeadLetterId like usp_DeadLetter_List. The payload
-- is left out: the message detail page shows it. Entries of deleted subscriptions are left out too:
-- they cannot be requeued (usp_DeadLetter_Requeue refuses them), so there is nothing to act on.
CREATE OR ALTER PROCEDURE broker.usp_Admin_DeadLetter_Search
    @TopicId         uniqueidentifier = NULL,
    @SubscriptionId  uniqueidentifier = NULL,
    @Reason          varchar(30) = NULL,
    @From            datetime2(3) = NULL,
    @To              datetime2(3) = NULL,
    @IncludeRequeued bit = 0,
    @BeforeId        bigint = NULL,
    @PageSize        int = 50
AS
BEGIN
    SET NOCOUNT ON;

    IF @PageSize IS NULL OR @PageSize NOT BETWEEN 1 AND 200
        THROW 50400, N'pageSize must be between 1 and 200.', 1;
    IF @From IS NOT NULL AND @To IS NOT NULL AND @From > @To
        THROW 50400, N'from must not be later than to.', 1;
    IF @Reason IS NOT NULL AND @Reason NOT IN ('MaxAttemptsExceeded', 'Expired', 'RejectedBySubscriber')
        THROW 50400, N'reason must be MaxAttemptsExceeded, Expired or RejectedBySubscriber.', 1;

    SELECT TOP (@PageSize)
           DeadLetterId, DeliveryId, MessageId, SubscriptionId, SubscriptionName, TopicId, TopicName, Reason,
           AttemptCount, LastError, FirstFailureAt, LastFailureAt, DeadLetteredAt, RequeuedAt, RequeuedBy,
           MessageType, CorrelationId, MessageCreatedAt
    FROM broker.vw_DeadLetterDetails d
    WHERE EXISTS (SELECT 1 FROM broker.Subscriptions s WHERE s.SubscriptionId = d.SubscriptionId AND s.Status <> 'Deleted')
      AND (@TopicId IS NULL OR TopicId = @TopicId)
      AND (@SubscriptionId IS NULL OR SubscriptionId = @SubscriptionId)
      AND (@Reason IS NULL OR Reason = @Reason)
      AND (@From IS NULL OR DeadLetteredAt >= @From)
      AND (@To IS NULL OR DeadLetteredAt <= @To)
      AND (@IncludeRequeued = 1 OR RequeuedAt IS NULL)
      AND (@BeforeId IS NULL OR DeadLetterId < @BeforeId)
    ORDER BY DeadLetterId DESC
    OPTION (RECOMPILE);
END
GO
GO

-- ===== MessageBroker.Infrastructure.db.Programmability.Procedures.Publish.sql
-- Publish and fan-out (spec section 8.1). The message and one delivery per Active or Paused
-- subscription are written in one transaction; the caller returns 201 only after this commits.
--
-- [Fix 2] Idempotency: a quick lookup handles the common retry. Two concurrent publishes with the
-- same key both miss the lookup; the unique filtered index rejects the second insert (2601/2627),
-- and the CATCH block returns the winner's MessageId instead of failing.
CREATE OR ALTER PROCEDURE broker.usp_Message_Publish
    @MessageId      uniqueidentifier,
    @TopicName      nvarchar(100),
    @AppId          uniqueidentifier,
    @MessageType    nvarchar(200),
    @CorrelationId  nvarchar(100),
    @IdempotencyKey nvarchar(100) = NULL,
    @Payload        nvarchar(max),
    @Properties     nvarchar(max) = NULL,
    @TtlSeconds     int = NULL
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    DECLARE @TopicId uniqueidentifier, @DefaultTtl int;
    SELECT @TopicId = TopicId, @DefaultTtl = DefaultTtlSeconds
    FROM broker.Topics WHERE Name = @TopicName AND IsDeleted = 0;

    IF @TopicId IS NULL
        THROW 50404, N'Topic was not found.', 1;
    IF NOT EXISTS (SELECT 1 FROM broker.fn_HasPermission(@AppId, 'Topic', @TopicId, 'Publish') WHERE Allowed = 1)
        THROW 50403, N'The application is not permitted to publish to this topic.', 1;

    DECLARE @ExistingId uniqueidentifier;
    IF @IdempotencyKey IS NOT NULL
    BEGIN
        SELECT @ExistingId = MessageId FROM broker.Messages
        WHERE TopicId = @TopicId AND PublisherAppId = @AppId AND IdempotencyKey = @IdempotencyKey;

        IF @ExistingId IS NOT NULL
        BEGIN
            SELECT @ExistingId AS MessageId,
                   (SELECT COUNT(*) FROM broker.Deliveries WHERE MessageId = @ExistingId) AS DeliveryCount,
                   CAST(1 AS bit) AS IsDuplicate;
            RETURN;
        END
    END

    DECLARE @Now datetime2(3) = SYSUTCDATETIME();
    DECLARE @Ttl int = COALESCE(@TtlSeconds, @DefaultTtl);
    DECLARE @ExpiresAt datetime2(3) = CASE WHEN @Ttl IS NULL THEN NULL ELSE DATEADD(second, @Ttl, @Now) END;
    DECLARE @DeliveryCount int;

    BEGIN TRY
        BEGIN TRAN;

        INSERT broker.Messages
            (MessageId, TopicId, MessageType, CorrelationId, PublisherAppId, IdempotencyKey, Payload, Properties, CreatedAt, ExpiresAt)
        VALUES
            (@MessageId, @TopicId, @MessageType, @CorrelationId, @AppId, @IdempotencyKey, @Payload, @Properties, @Now, @ExpiresAt);

        -- A delivery expires at the earlier of the message expiry and the subscription TTL.
        INSERT broker.Deliveries (MessageId, SubscriptionId, Status, AvailableAt, ExpiresAt, CreatedAt)
        SELECT @MessageId, s.SubscriptionId, 0, @Now,
               CASE
                   WHEN s.TtlSeconds IS NULL THEN @ExpiresAt
                   WHEN @ExpiresAt IS NULL OR DATEADD(second, s.TtlSeconds, @Now) < @ExpiresAt THEN DATEADD(second, s.TtlSeconds, @Now)
                   ELSE @ExpiresAt
               END,
               @Now
        FROM broker.Subscriptions s
        WHERE s.TopicId = @TopicId AND s.Status IN ('Active', 'Paused');

        SET @DeliveryCount = @@ROWCOUNT;

        COMMIT;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK;

        IF ERROR_NUMBER() IN (2601, 2627) AND @IdempotencyKey IS NOT NULL
        BEGIN
            SELECT @ExistingId = MessageId FROM broker.Messages
            WHERE TopicId = @TopicId AND PublisherAppId = @AppId AND IdempotencyKey = @IdempotencyKey;

            IF @ExistingId IS NOT NULL
            BEGIN
                SELECT @ExistingId AS MessageId,
                       (SELECT COUNT(*) FROM broker.Deliveries WHERE MessageId = @ExistingId) AS DeliveryCount,
                       CAST(1 AS bit) AS IsDuplicate;
                RETURN;
            END
        END;

        THROW;
    END CATCH

    SELECT @MessageId AS MessageId, @DeliveryCount AS DeliveryCount, CAST(0 AS bit) AS IsDuplicate;
END
GO
GO

-- ===== MessageBroker.Infrastructure.db.Programmability.Procedures.QueriesAndOps.sql
-- Traceability queries, DLQ listing, heartbeat and retention.

-- Message with its deliveries and every attempt (three result sets). Admins can read any message,
-- publishers only their own. @AppId NULL skips the check (broker-internal callers).
CREATE OR ALTER PROCEDURE broker.usp_Message_GetById
    @MessageId uniqueidentifier,
    @AppId     uniqueidentifier = NULL
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @PublisherAppId uniqueidentifier = (SELECT PublisherAppId FROM broker.Messages WHERE MessageId = @MessageId);
    IF @PublisherAppId IS NULL
        THROW 50404, N'Message was not found.', 1;
    IF @AppId IS NOT NULL AND @AppId <> @PublisherAppId
       AND NOT EXISTS (SELECT 1 FROM broker.Applications WHERE AppId = @AppId AND IsAdmin = 1 AND IsActive = 1)
        THROW 50403, N'Only Admins and the publishing application can read this message.', 1;

    SELECT m.MessageId, t.Name AS TopicName, m.MessageType, m.CorrelationId, m.PublisherAppId, m.IdempotencyKey,
           m.Properties, m.Payload, m.CreatedAt, m.ExpiresAt, ms.Status
    FROM broker.Messages m
    JOIN broker.Topics t ON t.TopicId = m.TopicId
    JOIN broker.vw_MessageStatus ms ON ms.MessageId = m.MessageId
    WHERE m.MessageId = @MessageId;

    SELECT d.DeliveryId, d.SubscriptionId, s.Name AS SubscriptionName, s.DeliveryMode, d.Status,
           d.AttemptCount, d.TotalAttemptCount, d.AvailableAt, d.LockedUntil, d.ExpiresAt, d.CompletedAt,
           dl.Reason AS DeadLetterReason
    FROM broker.Deliveries d
    JOIN broker.Subscriptions s ON s.SubscriptionId = d.SubscriptionId
    LEFT JOIN broker.DeadLetters dl ON dl.DeliveryId = d.DeliveryId AND dl.RequeuedAt IS NULL
    WHERE d.MessageId = @MessageId
    ORDER BY d.DeliveryId;

    SELECT a.AttemptId, a.DeliveryId, a.AttemptNumber, a.Channel, a.LeasedAt, a.EndedAt, a.Outcome,
           a.HttpStatusCode, a.DurationMs, a.ErrorCode, a.ErrorMessage, a.ErrorDetail
    FROM broker.DeliveryAttempts a
    JOIN broker.Deliveries d ON d.DeliveryId = a.DeliveryId
    WHERE d.MessageId = @MessageId
    ORDER BY a.DeliveryId, a.AttemptNumber;
END
GO

CREATE OR ALTER PROCEDURE broker.usp_Message_ListByCorrelation
    @CorrelationId nvarchar(100),
    @MaxRows       int = 500
AS
BEGIN
    SET NOCOUNT ON;
    SELECT TOP (@MaxRows)
           m.MessageId, t.Name AS TopicName, m.MessageType, m.CorrelationId, m.PublisherAppId,
           m.CreatedAt, m.ExpiresAt, ms.Status, ms.DeliveryCount
    FROM broker.Messages m
    JOIN broker.Topics t ON t.TopicId = m.TopicId
    JOIN broker.vw_MessageStatus ms ON ms.MessageId = m.MessageId
    WHERE m.CorrelationId = @CorrelationId
    ORDER BY m.MessageSeq;
END
GO

-- Keyset paging, newest first: pass the smallest DeadLetterId of the previous page as @BeforeId.
-- Admins and applications with Receive on the subscription (its owner) may list.
CREATE OR ALTER PROCEDURE broker.usp_DeadLetter_List
    @SubscriptionId  uniqueidentifier,
    @AppId           uniqueidentifier = NULL,
    @PageSize        int = 50,
    @BeforeId        bigint = NULL,
    @IncludeRequeued bit = 0
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM broker.Subscriptions WHERE SubscriptionId = @SubscriptionId)
        THROW 50404, N'Subscription was not found.', 1;
    IF @AppId IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM broker.fn_HasPermission(@AppId, 'Subscription', @SubscriptionId, 'Receive') WHERE Allowed = 1)
        THROW 50403, N'The application is not permitted to view this subscription''s dead letters.', 1;

    SELECT TOP (@PageSize) *
    FROM broker.vw_DeadLetterDetails
    WHERE SubscriptionId = @SubscriptionId
      AND (@IncludeRequeued = 1 OR RequeuedAt IS NULL)
      AND (@BeforeId IS NULL OR DeadLetterId < @BeforeId)
    ORDER BY DeadLetterId DESC;
END
GO

CREATE OR ALTER PROCEDURE broker.usp_Heartbeat_Write
    @InstanceId nvarchar(200)
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    UPDATE broker.BrokerHeartbeats SET LastBeatAt = SYSUTCDATETIME() WHERE InstanceId = @InstanceId;
    IF @@ROWCOUNT = 0
        INSERT broker.BrokerHeartbeats (InstanceId, LastBeatAt) VALUES (@InstanceId, SYSUTCDATETIME());
END
GO

-- Returns the newest heartbeat and the database clock, so the age is measured on one clock.
CREATE OR ALTER PROCEDURE broker.usp_Heartbeat_GetLatest
AS
BEGIN
    SET NOCOUNT ON;
    -- DbNow at LastBeatAt's precision: datetime2(3) rounds, and a beat written a moment ago could
    -- otherwise read as slightly in the future.
    SELECT MAX(LastBeatAt) AS LastBeatAt, CAST(SYSUTCDATETIME() AS datetime2(3)) AS DbNow FROM broker.BrokerHeartbeats;
END
GO

-- Hourly purge (spec section 7, retention). Deletes in batches to avoid lock escalation:
--   * Completed and Cancelled deliveries, with attempts, @CompletedDays after completion
--   * Dead-lettered deliveries @DeadLetterDays after dead-lettering
--   * Messages with no remaining deliveries, @CompletedDays after creation
--     (covers messages that never had subscriptions, and keeps any message still in the DLQ)
CREATE OR ALTER PROCEDURE broker.usp_Retention_Purge
    @CompletedDays  int = 14,
    @DeadLetterDays int = 90,
    @BatchSize      int = 5000
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    DECLARE @Now datetime2(3) = SYSUTCDATETIME();
    DECLARE @CompletedCutoff datetime2(3) = DATEADD(day, -@CompletedDays, @Now);
    DECLARE @DeadLetterCutoff datetime2(3) = DATEADD(day, -@DeadLetterDays, @Now);
    -- Each delivery has a handful of attempts, so fewer deliveries per batch keeps every DELETE small.
    DECLARE @DeliveryBatch int = CASE WHEN @BatchSize / 5 < 1 THEN 1 ELSE @BatchSize / 5 END;
    DECLARE @DeliveriesDeleted int = 0, @MessagesDeleted int = 0, @Rows int;
    DECLARE @Batch TABLE (DeliveryId bigint PRIMARY KEY);

    WHILE 1 = 1
    BEGIN
        DELETE @Batch;

        INSERT @Batch (DeliveryId)
        SELECT TOP (@DeliveryBatch) d.DeliveryId
        FROM broker.Deliveries d
        WHERE (d.Status IN (2, 4) AND d.CompletedAt < @CompletedCutoff)
           OR (d.Status = 3 AND EXISTS (SELECT 1 FROM broker.DeadLetters dl
                                        WHERE dl.DeliveryId = d.DeliveryId AND dl.RequeuedAt IS NULL
                                          AND dl.DeadLetteredAt < @DeadLetterCutoff));

        IF @@ROWCOUNT = 0 BREAK;

        BEGIN TRAN;
        DELETE a FROM broker.DeliveryAttempts a JOIN @Batch b ON b.DeliveryId = a.DeliveryId;
        DELETE dl FROM broker.DeadLetters dl JOIN @Batch b ON b.DeliveryId = dl.DeliveryId;
        DELETE d FROM broker.Deliveries d JOIN @Batch b ON b.DeliveryId = d.DeliveryId;
        SET @DeliveriesDeleted += @@ROWCOUNT;
        COMMIT;
    END

    WHILE 1 = 1
    BEGIN
        DELETE TOP (@BatchSize) m
        FROM broker.Messages m
        WHERE m.CreatedAt < @CompletedCutoff
          AND NOT EXISTS (SELECT 1 FROM broker.Deliveries d WHERE d.MessageId = m.MessageId);

        SET @Rows = @@ROWCOUNT;
        SET @MessagesDeleted += @Rows;
        IF @Rows < @BatchSize BREAK;
    END

    DELETE broker.BrokerHeartbeats WHERE LastBeatAt < DATEADD(day, -1, @Now);

    SELECT @DeliveriesDeleted AS DeliveriesDeleted, @MessagesDeleted AS MessagesDeleted;
END
GO

-- Readiness probe: proves the connection works and the broker schema is deployed.
CREATE OR ALTER PROCEDURE broker.usp_Health_Ping
AS
BEGIN
    SET NOCOUNT ON;
    SELECT 1 AS Ok;
END
GO
GO

-- ===== MessageBroker.Infrastructure.db.Programmability.Procedures.Queue.sql
-- Lease, settle, expiry and requeue (spec sections 7, 8 and 10).
-- Every time comes from SYSUTCDATETIME() so the database clock alone decides leases and retries [Fix 4].

-- Throws 50404 when the delivery does not exist, 50403 when @AppId may not settle it.
-- @AppId NULL means the broker itself (dispatcher, maintenance).
CREATE OR ALTER PROCEDURE broker.usp_Delivery_CheckAccess
    @DeliveryId bigint,
    @AppId      uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @SubscriptionId uniqueidentifier = (SELECT SubscriptionId FROM broker.Deliveries WHERE DeliveryId = @DeliveryId);
    IF @SubscriptionId IS NULL
        THROW 50404, N'Delivery was not found.', 1;

    IF @AppId IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM broker.fn_HasPermission(@AppId, 'Subscription', @SubscriptionId, 'Receive') WHERE Allowed = 1)
        THROW 50403, N'The application is not permitted to settle deliveries of this subscription.', 1;
END
GO

-- Shared failure path for NACK, failed webhook calls and lease expiry. The caller must hold an
-- update lock on the Leased delivery inside its own transaction.
-- Every read or write of one delivery's DeliveryAttempts and DeadLetters rows seeks
-- UQ_DeliveryAttempts_Number or IX_DeadLetters_Delivery: FORCESEEK on reads, an INDEX hint in
-- the FROM clause of updates (FORCESEEK is not allowed on update targets). On a small table the optimizer would
-- otherwise scan the clustered index, and two settles of different deliveries deadlock on each
-- other's attempt rows (seen with concurrent webhook NACKs).
CREATE OR ALTER PROCEDURE broker.usp_Delivery_RecordFailure
    @DeliveryId      bigint,
    @Now             datetime2(3),
    @Outcome         varchar(20),
    @ErrorCode       nvarchar(100),
    @ErrorMessage    nvarchar(1000),
    @ErrorDetail     nvarchar(max),
    @HttpStatusCode  int,
    @DeadLetter      bit,
    @DeadLettered    bit OUTPUT,
    @NextAvailableAt datetime2(3) OUTPUT
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    DECLARE @AttemptCount int, @MaxAttempts int, @BaseDelay int, @MaxDelay int,
            @MessageId uniqueidentifier, @SubscriptionId uniqueidentifier, @TopicId uniqueidentifier;

    SELECT @AttemptCount = d.AttemptCount, @MaxAttempts = s.MaxAttempts,
           @BaseDelay = s.RetryBaseDelaySeconds, @MaxDelay = s.RetryMaxDelaySeconds,
           @MessageId = d.MessageId, @SubscriptionId = d.SubscriptionId, @TopicId = s.TopicId
    FROM broker.Deliveries d
    JOIN broker.Subscriptions s ON s.SubscriptionId = d.SubscriptionId
    WHERE d.DeliveryId = @DeliveryId;

    UPDATE a
    SET EndedAt = @Now,
        Outcome = @Outcome,
        HttpStatusCode = @HttpStatusCode,
        DurationMs = DATEDIFF(millisecond, LeasedAt, @Now),
        ErrorCode = @ErrorCode,
        ErrorMessage = @ErrorMessage,
        ErrorDetail = @ErrorDetail
    FROM broker.DeliveryAttempts a WITH (INDEX (UQ_DeliveryAttempts_Number))
    WHERE a.DeliveryId = @DeliveryId AND a.EndedAt IS NULL;

    IF @DeadLetter = 1 OR @AttemptCount >= @MaxAttempts
    BEGIN
        UPDATE broker.Deliveries SET Status = 3, LockToken = NULL, LockedUntil = NULL WHERE DeliveryId = @DeliveryId;

        -- First failure of the current cycle: attempts since the last requeue, if any.
        DECLARE @LastRequeue datetime2(3) = (SELECT MAX(RequeuedAt) FROM broker.DeadLetters WITH (FORCESEEK) WHERE DeliveryId = @DeliveryId);

        INSERT broker.DeadLetters
            (DeliveryId, MessageId, SubscriptionId, TopicId, Reason, AttemptCount, LastError, FirstFailureAt, LastFailureAt, DeadLetteredAt)
        SELECT @DeliveryId, @MessageId, @SubscriptionId, @TopicId,
               CASE WHEN @DeadLetter = 1 THEN 'RejectedBySubscriber' ELSE 'MaxAttemptsExceeded' END,
               @AttemptCount,
               COALESCE(@ErrorMessage, @ErrorCode),
               (SELECT MIN(EndedAt) FROM broker.DeliveryAttempts WITH (FORCESEEK)
                WHERE DeliveryId = @DeliveryId
                  AND Outcome IN ('Nacked', 'LeaseExpired')
                  AND (@LastRequeue IS NULL OR LeasedAt >= @LastRequeue)),
               @Now,
               @Now;

        SET @DeadLettered = 1;
        SET @NextAvailableAt = NULL;
    END
    ELSE
    BEGIN
        -- delay(n) = min(base * 2^(n-1), max) * (1 +/- 0.2 jitter), spec section 10.
        DECLARE @DelaySeconds float = @BaseDelay * POWER(CAST(2 AS float), @AttemptCount - 1);
        IF @DelaySeconds > @MaxDelay SET @DelaySeconds = @MaxDelay;
        DECLARE @DelayMs int = CAST(@DelaySeconds * 1000.0 * (0.8 + 0.4 * RAND(CHECKSUM(NEWID()))) AS int);

        SET @NextAvailableAt = DATEADD(millisecond, @DelayMs, @Now);
        SET @DeadLettered = 0;

        UPDATE broker.Deliveries
        SET Status = 0, LockToken = NULL, LockedUntil = NULL, AvailableAt = @NextAvailableAt
        WHERE DeliveryId = @DeliveryId;
    END
END
GO

-- [Fix 3] The spec's atomic lease statement plus the attempt rows, in one transaction.
-- [Fix 12] Paused subscriptions lease nothing, whether pushed or pulled.
CREATE OR ALTER PROCEDURE broker.usp_Delivery_Lease
    @SubscriptionId uniqueidentifier,
    @MaxMessages    int,
    @Channel        varchar(10),
    @AppId          uniqueidentifier = NULL
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    DECLARE @Status varchar(10), @Mode varchar(10), @LockSeconds int;
    SELECT @Status = Status, @Mode = DeliveryMode, @LockSeconds = LockDurationSeconds
    FROM broker.Subscriptions WHERE SubscriptionId = @SubscriptionId;

    IF @Status IS NULL OR @Status = 'Deleted'
        THROW 50404, N'Subscription was not found.', 1;
    IF @AppId IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM broker.fn_HasPermission(@AppId, 'Subscription', @SubscriptionId, 'Receive') WHERE Allowed = 1)
        THROW 50403, N'The application is not permitted to receive from this subscription.', 1;
    IF @Channel = 'Pull' AND @Mode <> 'Pull'
        THROW 50409, N'The subscription does not use Pull delivery.', 1;
    IF @MaxMessages < 1 OR @MaxMessages > 256
        THROW 50400, N'maxMessages is out of range.', 1;

    DECLARE @Leased TABLE
    (
        DeliveryId        bigint PRIMARY KEY,
        MessageId         uniqueidentifier,
        LockToken         uniqueidentifier,
        LockedUntil       datetime2(3),
        AttemptCount      int,
        TotalAttemptCount int
    );
    DECLARE @Now datetime2(3) = SYSUTCDATETIME();

    IF @Status = 'Active'
    BEGIN
        BEGIN TRAN;

        WITH next AS
        (
            SELECT TOP (@MaxMessages) DeliveryId, MessageId, Status, LockToken, LockedUntil, AttemptCount, TotalAttemptCount
            FROM broker.Deliveries WITH (UPDLOCK, READPAST, ROWLOCK)
            WHERE SubscriptionId = @SubscriptionId
              AND Status = 0
              AND AvailableAt <= @Now
              AND (ExpiresAt IS NULL OR ExpiresAt > @Now)
            ORDER BY AvailableAt, DeliveryId
        )
        UPDATE next
        SET Status = 1,
            LockToken = NEWID(),
            LockedUntil = DATEADD(second, @LockSeconds, @Now),
            AttemptCount = AttemptCount + 1,
            TotalAttemptCount = TotalAttemptCount + 1
        OUTPUT inserted.DeliveryId, inserted.MessageId, inserted.LockToken, inserted.LockedUntil,
               inserted.AttemptCount, inserted.TotalAttemptCount
        INTO @Leased;

        INSERT broker.DeliveryAttempts (DeliveryId, AttemptNumber, Channel, LeasedAt)
        SELECT DeliveryId, TotalAttemptCount, @Channel, @Now FROM @Leased;

        COMMIT;
    END

    SELECT l.DeliveryId, l.LockToken, l.LockedUntil, l.AttemptCount AS Attempt,
           m.MessageId, m.MessageType, m.CorrelationId, m.CreatedAt, m.Properties, m.Payload
    FROM @Leased l
    JOIN broker.Messages m ON m.MessageId = l.MessageId
    ORDER BY l.DeliveryId;
END
GO

-- Spec settle statement. 0 rows means the lease was lost: 50410, which the API returns as 410 Gone.
CREATE OR ALTER PROCEDURE broker.usp_Delivery_Ack
    @DeliveryId     bigint,
    @LockToken      uniqueidentifier,
    @AppId          uniqueidentifier = NULL,
    @HttpStatusCode int = NULL
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    EXEC broker.usp_Delivery_CheckAccess @DeliveryId, @AppId;

    DECLARE @Now datetime2(3) = SYSUTCDATETIME();

    BEGIN TRAN;

    UPDATE broker.Deliveries
    SET Status = 2, CompletedAt = @Now, LockToken = NULL, LockedUntil = NULL
    WHERE DeliveryId = @DeliveryId
      AND LockToken = @LockToken
      AND Status = 1
      AND LockedUntil > @Now;

    IF @@ROWCOUNT = 0
    BEGIN
        ROLLBACK;
        THROW 50410, N'The lease was lost: the lock token is stale or the lease has expired.', 1;
    END

    UPDATE a
    SET EndedAt = @Now, Outcome = 'Acked', HttpStatusCode = @HttpStatusCode, DurationMs = DATEDIFF(millisecond, LeasedAt, @Now)
    FROM broker.DeliveryAttempts a WITH (INDEX (UQ_DeliveryAttempts_Number))
    WHERE a.DeliveryId = @DeliveryId AND a.EndedAt IS NULL;

    COMMIT;

    -- For the admin activity feed.
    SELECT MessageId FROM broker.Deliveries WHERE DeliveryId = @DeliveryId;
END
GO

CREATE OR ALTER PROCEDURE broker.usp_Delivery_Nack
    @DeliveryId     bigint,
    @LockToken      uniqueidentifier,
    @AppId          uniqueidentifier = NULL,
    @ErrorCode      nvarchar(100) = NULL,
    @ErrorMessage   nvarchar(1000) = NULL,
    @ErrorDetail    nvarchar(max) = NULL,
    @HttpStatusCode int = NULL,
    @DeadLetter     bit = 0
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    EXEC broker.usp_Delivery_CheckAccess @DeliveryId, @AppId;

    DECLARE @Now datetime2(3) = SYSUTCDATETIME(), @DeadLettered bit, @NextAvailableAt datetime2(3);

    BEGIN TRAN;

    IF NOT EXISTS (SELECT 1 FROM broker.Deliveries WITH (UPDLOCK, ROWLOCK)
                   WHERE DeliveryId = @DeliveryId AND LockToken = @LockToken AND Status = 1 AND LockedUntil > @Now)
    BEGIN
        ROLLBACK;
        THROW 50410, N'The lease was lost: the lock token is stale or the lease has expired.', 1;
    END

    EXEC broker.usp_Delivery_RecordFailure
        @DeliveryId, @Now, 'Nacked', @ErrorCode, @ErrorMessage, @ErrorDetail, @HttpStatusCode, @DeadLetter,
        @DeadLettered OUTPUT, @NextAvailableAt OUTPUT;

    COMMIT;

    SELECT @DeadLettered AS DeadLettered, @NextAvailableAt AS NextAvailableAt,
           (SELECT MessageId FROM broker.Deliveries WHERE DeliveryId = @DeliveryId) AS MessageId;
END
GO

-- Extends the lease by the subscription's lock duration from now (at most 600 seconds).
CREATE OR ALTER PROCEDURE broker.usp_Delivery_Renew
    @DeliveryId bigint,
    @LockToken  uniqueidentifier,
    @AppId      uniqueidentifier = NULL
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    EXEC broker.usp_Delivery_CheckAccess @DeliveryId, @AppId;

    DECLARE @Now datetime2(3) = SYSUTCDATETIME();
    DECLARE @Renewed TABLE (LockedUntil datetime2(3));

    UPDATE d
    SET LockedUntil = DATEADD(second, s.LockDurationSeconds, @Now)
    OUTPUT inserted.LockedUntil INTO @Renewed
    FROM broker.Deliveries d
    JOIN broker.Subscriptions s ON s.SubscriptionId = d.SubscriptionId
    WHERE d.DeliveryId = @DeliveryId
      AND d.LockToken = @LockToken
      AND d.Status = 1
      AND d.LockedUntil > @Now;

    IF NOT EXISTS (SELECT 1 FROM @Renewed)
        THROW 50410, N'The lease was lost: the lock token is stale or the lease has expired.', 1;

    SELECT LockedUntil FROM @Renewed;
END
GO

-- Maintenance: leases whose LockedUntil has passed count as a failed attempt (LeaseExpired) and are
-- retried or dead-lettered. One row per transaction keeps locks short; READPAST skips rows a
-- concurrent ACK is settling, which then wins or loses on LockedUntil.
CREATE OR ALTER PROCEDURE broker.usp_Delivery_ExpireLeases
    @MaxRows int = 500
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    DECLARE @Processed int = 0, @DeliveryId bigint, @Now datetime2(3), @DeadLettered bit, @NextAvailableAt datetime2(3);

    WHILE @Processed < @MaxRows
    BEGIN
        SET @DeliveryId = NULL;
        SET @Now = SYSUTCDATETIME();

        BEGIN TRAN;

        SELECT TOP (1) @DeliveryId = DeliveryId
        FROM broker.Deliveries WITH (UPDLOCK, READPAST, ROWLOCK)
        WHERE Status = 1 AND LockedUntil <= @Now
        ORDER BY LockedUntil;

        IF @DeliveryId IS NULL
        BEGIN
            COMMIT;
            BREAK;
        END

        EXEC broker.usp_Delivery_RecordFailure
            @DeliveryId, @Now, 'LeaseExpired', N'LeaseExpired', N'The lease expired before the delivery was settled.',
            NULL, NULL, 0, @DeadLettered OUTPUT, @NextAvailableAt OUTPUT;

        COMMIT;
        SET @Processed += 1;
    END

    SELECT @Processed AS ExpiredCount;
END
GO

-- Maintenance: a Pending delivery past ExpiresAt is never handed out; it is dead-lettered as
-- Expired. A Leased delivery may finish its current attempt.
CREATE OR ALTER PROCEDURE broker.usp_Delivery_ExpirePending
    @MaxRows int = 1000
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    DECLARE @Now datetime2(3) = SYSUTCDATETIME();
    DECLARE @Expired TABLE (DeliveryId bigint PRIMARY KEY, MessageId uniqueidentifier, SubscriptionId uniqueidentifier, AttemptCount int);

    BEGIN TRAN;

    WITH due AS
    (
        SELECT TOP (@MaxRows) DeliveryId, MessageId, SubscriptionId, AttemptCount, Status
        FROM broker.Deliveries WITH (UPDLOCK, READPAST, ROWLOCK)
        WHERE Status = 0 AND ExpiresAt <= @Now
    )
    UPDATE due SET Status = 3
    OUTPUT inserted.DeliveryId, inserted.MessageId, inserted.SubscriptionId, inserted.AttemptCount INTO @Expired;

    INSERT broker.DeadLetters
        (DeliveryId, MessageId, SubscriptionId, TopicId, Reason, AttemptCount, LastError, FirstFailureAt, LastFailureAt, DeadLetteredAt)
    SELECT e.DeliveryId, e.MessageId, e.SubscriptionId, s.TopicId, 'Expired', e.AttemptCount,
           N'The delivery expired before it was delivered.',
           COALESCE(f.FirstFailureAt, @Now), @Now, @Now
    FROM @Expired e
    JOIN broker.Subscriptions s ON s.SubscriptionId = e.SubscriptionId
    OUTER APPLY (SELECT MIN(a.EndedAt) AS FirstFailureAt
                 FROM broker.DeliveryAttempts a WITH (FORCESEEK)
                 WHERE a.DeliveryId = e.DeliveryId
                   AND a.Outcome IN ('Nacked', 'LeaseExpired')
                   AND a.LeasedAt >= COALESCE((SELECT MAX(RequeuedAt) FROM broker.DeadLetters r WITH (FORCESEEK) WHERE r.DeliveryId = e.DeliveryId), '0001-01-01')) f;

    COMMIT;

    SELECT COUNT(*) AS ExpiredCount FROM @Expired;
END
GO

-- [Fix 1] Requeue resets AttemptCount (the retry budget) but not TotalAttemptCount, so attempt
-- numbers keep increasing, and closes the open DLQ row instead of deleting it. ExpiresAt is cleared:
-- an operator requeue is an explicit decision to deliver again.
CREATE OR ALTER PROCEDURE broker.usp_DeadLetter_Requeue
    @DeliveryId bigint,
    @RequeuedBy uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    DECLARE @Now datetime2(3) = SYSUTCDATETIME(), @Status tinyint, @SubscriptionStatus varchar(10);

    BEGIN TRAN;

    SELECT @Status = d.Status, @SubscriptionStatus = s.Status
    FROM broker.Deliveries d WITH (UPDLOCK, ROWLOCK)
    JOIN broker.Subscriptions s ON s.SubscriptionId = d.SubscriptionId
    WHERE d.DeliveryId = @DeliveryId;

    IF @Status IS NULL
    BEGIN
        ROLLBACK;
        THROW 50404, N'Delivery was not found.', 1;
    END
    IF @Status <> 3
    BEGIN
        ROLLBACK;
        THROW 50409, N'The delivery is not in the dead letter queue.', 1;
    END
    IF @SubscriptionStatus = 'Deleted'
    BEGIN
        ROLLBACK;
        THROW 50409, N'The subscription has been deleted.', 1;
    END

    UPDATE broker.Deliveries
    SET Status = 0, AttemptCount = 0, AvailableAt = @Now, ExpiresAt = NULL, LockToken = NULL, LockedUntil = NULL
    WHERE DeliveryId = @DeliveryId;

    UPDATE dl SET RequeuedAt = @Now, RequeuedBy = @RequeuedBy
    FROM broker.DeadLetters dl WITH (INDEX (IX_DeadLetters_Delivery))
    WHERE dl.DeliveryId = @DeliveryId AND dl.RequeuedAt IS NULL;

    COMMIT;

    SELECT MessageId FROM broker.Deliveries WHERE DeliveryId = @DeliveryId;
END
GO
GO

-- ===== MessageBroker.Infrastructure.db.Programmability.Procedures.TopicsAndSubscriptions.sql
-- Topics and subscriptions.

CREATE OR ALTER PROCEDURE broker.usp_Topic_Create
    @TopicId           uniqueidentifier,
    @Name              nvarchar(100),
    @DefaultTtlSeconds int = NULL
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    IF EXISTS (SELECT 1 FROM broker.Topics WHERE Name = @Name AND IsDeleted = 0)
        THROW 50409, N'A topic with this name already exists.', 1;

    INSERT broker.Topics (TopicId, Name, DefaultTtlSeconds) VALUES (@TopicId, @Name, @DefaultTtlSeconds);

    SELECT TopicId, Name, DefaultTtlSeconds, CreatedAt FROM broker.Topics WHERE TopicId = @TopicId;
END
GO

CREATE OR ALTER PROCEDURE broker.usp_Topic_Get
    @TopicId uniqueidentifier = NULL,
    @Name    nvarchar(100) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SELECT TopicId, Name, DefaultTtlSeconds, CreatedAt
    FROM broker.Topics
    WHERE IsDeleted = 0
      AND (TopicId = @TopicId OR (@TopicId IS NULL AND Name = @Name));
END
GO

CREATE OR ALTER PROCEDURE broker.usp_Topic_List
AS
BEGIN
    SET NOCOUNT ON;
    SELECT TopicId, Name, DefaultTtlSeconds, CreatedAt FROM broker.Topics WHERE IsDeleted = 0 ORDER BY Name;
END
GO

CREATE OR ALTER PROCEDURE broker.usp_Topic_Update
    @TopicId           uniqueidentifier,
    @DefaultTtlSeconds int = NULL
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    UPDATE broker.Topics SET DefaultTtlSeconds = @DefaultTtlSeconds WHERE TopicId = @TopicId AND IsDeleted = 0;
    IF @@ROWCOUNT = 0
        THROW 50404, N'Topic was not found.', 1;

    SELECT TopicId, Name, DefaultTtlSeconds, CreatedAt FROM broker.Topics WHERE TopicId = @TopicId;
END
GO

-- Spec section 6: a topic can be deleted only when it has no subscriptions. Deletion is soft so
-- message history keeps its foreign key.
CREATE OR ALTER PROCEDURE broker.usp_Topic_Delete
    @TopicId uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    BEGIN TRAN;

    IF NOT EXISTS (SELECT 1 FROM broker.Topics WITH (UPDLOCK, HOLDLOCK) WHERE TopicId = @TopicId AND IsDeleted = 0)
    BEGIN
        ROLLBACK;
        THROW 50404, N'Topic was not found.', 1;
    END

    IF EXISTS (SELECT 1 FROM broker.Subscriptions WHERE TopicId = @TopicId AND Status <> 'Deleted')
    BEGIN
        ROLLBACK;
        THROW 50409, N'The topic still has subscriptions. Delete them first.', 1;
    END

    UPDATE broker.Topics SET IsDeleted = 1 WHERE TopicId = @TopicId;
    DELETE broker.AppPermissions WHERE ResourceType = 'Topic' AND ResourceId = @TopicId;

    COMMIT;
END
GO

CREATE OR ALTER PROCEDURE broker.usp_Subscription_Create
    @SubscriptionId          uniqueidentifier,
    @TopicId                 uniqueidentifier,
    @Name                    nvarchar(100),
    @OwnerAppId              uniqueidentifier,
    @DeliveryMode            varchar(10),
    @WebhookUrl              nvarchar(2000) = NULL,
    @WebhookSecret           nvarchar(1000) = NULL,
    @WebhookTimeoutSeconds   int,
    @MaxConcurrentDeliveries int,
    @MaxAttempts             int,
    @LockDurationSeconds     int,
    @RetryBaseDelaySeconds   int,
    @RetryMaxDelaySeconds    int,
    @TtlSeconds              int = NULL
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    IF NOT EXISTS (SELECT 1 FROM broker.Topics WHERE TopicId = @TopicId AND IsDeleted = 0)
        THROW 50404, N'Topic was not found.', 1;
    IF NOT EXISTS (SELECT 1 FROM broker.Applications WHERE AppId = @OwnerAppId)
        THROW 50404, N'Owner application was not found.', 1;
    IF EXISTS (SELECT 1 FROM broker.Subscriptions WHERE TopicId = @TopicId AND Name = @Name AND Status <> 'Deleted')
        THROW 50409, N'A subscription with this name already exists on the topic.', 1;

    BEGIN TRAN;

    INSERT broker.Subscriptions
        (SubscriptionId, TopicId, Name, OwnerAppId, Status, DeliveryMode, WebhookUrl, WebhookSecret,
         WebhookTimeoutSeconds, MaxConcurrentDeliveries, MaxAttempts, LockDurationSeconds,
         RetryBaseDelaySeconds, RetryMaxDelaySeconds, TtlSeconds)
    VALUES
        (@SubscriptionId, @TopicId, @Name, @OwnerAppId, 'Active', @DeliveryMode, @WebhookUrl, @WebhookSecret,
         @WebhookTimeoutSeconds, @MaxConcurrentDeliveries, @MaxAttempts, @LockDurationSeconds,
         @RetryBaseDelaySeconds, @RetryMaxDelaySeconds, @TtlSeconds);

    -- The owning application can receive from its own subscription.
    INSERT broker.AppPermissions (AppId, ResourceType, ResourceId, Permission)
    VALUES (@OwnerAppId, 'Subscription', @SubscriptionId, 'Receive');

    COMMIT;

    SELECT * FROM broker.vw_SubscriptionDetails WHERE SubscriptionId = @SubscriptionId;
END
GO

CREATE OR ALTER PROCEDURE broker.usp_Subscription_Get
    @SubscriptionId uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;
    SELECT * FROM broker.vw_SubscriptionDetails WHERE SubscriptionId = @SubscriptionId AND Status <> 'Deleted';
END
GO

CREATE OR ALTER PROCEDURE broker.usp_Subscription_List
    @TopicId uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM broker.Topics WHERE TopicId = @TopicId AND IsDeleted = 0)
        THROW 50404, N'Topic was not found.', 1;

    SELECT * FROM broker.vw_SubscriptionDetails WHERE TopicId = @TopicId AND Status <> 'Deleted' ORDER BY Name;
END
GO

-- Full replacement of the changeable settings. The service merges PATCH input and validates it first.
-- The delivery mode cannot change; create a new subscription instead.
CREATE OR ALTER PROCEDURE broker.usp_Subscription_Update
    @SubscriptionId          uniqueidentifier,
    @Status                  varchar(10),
    @WebhookUrl              nvarchar(2000) = NULL,
    @WebhookTimeoutSeconds   int,
    @MaxConcurrentDeliveries int,
    @MaxAttempts             int,
    @LockDurationSeconds     int,
    @RetryBaseDelaySeconds   int,
    @RetryMaxDelaySeconds    int,
    @TtlSeconds              int = NULL
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    IF @Status NOT IN ('Active', 'Paused')
        THROW 50400, N'Status must be Active or Paused.', 1;

    UPDATE broker.Subscriptions
    SET Status = @Status,
        WebhookUrl = @WebhookUrl,
        WebhookTimeoutSeconds = @WebhookTimeoutSeconds,
        MaxConcurrentDeliveries = @MaxConcurrentDeliveries,
        MaxAttempts = @MaxAttempts,
        LockDurationSeconds = @LockDurationSeconds,
        RetryBaseDelaySeconds = @RetryBaseDelaySeconds,
        RetryMaxDelaySeconds = @RetryMaxDelaySeconds,
        TtlSeconds = @TtlSeconds,
        UpdatedAt = SYSUTCDATETIME()
    WHERE SubscriptionId = @SubscriptionId AND Status <> 'Deleted';

    IF @@ROWCOUNT = 0
        THROW 50404, N'Subscription was not found.', 1;

    SELECT * FROM broker.vw_SubscriptionDetails WHERE SubscriptionId = @SubscriptionId;
END
GO

-- Soft delete. Pending and Leased deliveries become Cancelled (terminal); an open attempt is closed
-- as Cancelled, so a late ACK with the old lock token gets 410.
CREATE OR ALTER PROCEDURE broker.usp_Subscription_Delete
    @SubscriptionId uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    DECLARE @Now datetime2(3) = SYSUTCDATETIME();

    BEGIN TRAN;

    UPDATE broker.Subscriptions SET Status = 'Deleted', UpdatedAt = @Now
    WHERE SubscriptionId = @SubscriptionId AND Status <> 'Deleted';

    IF @@ROWCOUNT = 0
    BEGIN
        ROLLBACK;
        THROW 50404, N'Subscription was not found.', 1;
    END

    UPDATE a SET EndedAt = @Now, Outcome = 'Cancelled', DurationMs = DATEDIFF(millisecond, a.LeasedAt, @Now)
    FROM broker.DeliveryAttempts a
    JOIN broker.Deliveries d ON d.DeliveryId = a.DeliveryId
    WHERE d.SubscriptionId = @SubscriptionId AND d.Status = 1 AND a.EndedAt IS NULL;

    UPDATE broker.Deliveries
    SET Status = 4, CompletedAt = @Now, LockToken = NULL, LockedUntil = NULL
    WHERE SubscriptionId = @SubscriptionId AND Status IN (0, 1);

    DELETE broker.AppPermissions WHERE ResourceType = 'Subscription' AND ResourceId = @SubscriptionId;

    COMMIT;
END
GO

-- [Fix 7] The current secret becomes the previous one and stays valid for 24 hours; during that
-- window the webhook sender signs with both.
CREATE OR ALTER PROCEDURE broker.usp_Subscription_RotateSecret
    @SubscriptionId uniqueidentifier,
    @NewSecret      nvarchar(1000)
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    DECLARE @Mode varchar(10) = (SELECT DeliveryMode FROM broker.Subscriptions
                                 WHERE SubscriptionId = @SubscriptionId AND Status <> 'Deleted');
    IF @Mode IS NULL
        THROW 50404, N'Subscription was not found.', 1;
    IF @Mode <> 'Webhook'
        THROW 50400, N'Only Webhook subscriptions have a signing secret.', 1;

    UPDATE broker.Subscriptions
    SET PreviousWebhookSecret = WebhookSecret,
        PreviousSecretExpiresAt = DATEADD(hour, 24, SYSUTCDATETIME()),
        WebhookSecret = @NewSecret,
        UpdatedAt = SYSUTCDATETIME()
    WHERE SubscriptionId = @SubscriptionId;

    SELECT * FROM broker.vw_SubscriptionDetails WHERE SubscriptionId = @SubscriptionId;
END
GO

-- Push subscriptions for the lease loop.
CREATE OR ALTER PROCEDURE broker.usp_Subscription_ListActivePush
AS
BEGIN
    SET NOCOUNT ON;
    SELECT * FROM broker.vw_ActivePushSubscriptions;
END
GO
GO

-- ===== Bootstrap data
BEGIN TRANSACTION;

DECLARE @Key varchar(200) = LTRIM(RTRIM('$(AdminApiKey)'));
DECLARE @AdminName nvarchar(100) = COALESCE(NULLIF(LTRIM(RTRIM(N'$(AdminName)')), N''), N'broker-admin');
IF @Key = ''
    PRINT N'AdminApiKey is empty, so no Admin key was added. Set Broker:Bootstrap:AdminApiKey instead.';
ELSE IF LEN(@Key) < 18 OR LEFT(@Key, 4) COLLATE Latin1_General_BIN2 <> 'mbk_' OR SUBSTRING(@Key, 17, 1) <> '_'
    THROW 50400, N'AdminApiKey is not a broker API key. Create one with: dotnet run --project src/MessageBroker.Api -- new-api-key', 1;
ELSE
BEGIN
    DECLARE @AppId uniqueidentifier = NEWID(), @KeyId uniqueidentifier = NEWID();
    DECLARE @Prefix varchar(32) = LEFT(@Key, 16), @Hash varbinary(32) = HASHBYTES('SHA2_256', @Key);
    EXEC broker.usp_Application_EnsureBootstrapAdmin @AppId, @AdminName, @KeyId, @Prefix, @Hash;
    PRINT N'Admin application ' + @AdminName + N' has key ' + @Prefix;
END

DECLARE @Hosts broker.HostList;
INSERT @Hosts (Host)
SELECT DISTINCT LOWER(LTRIM(RTRIM(value))) FROM STRING_SPLIT(N'$(WebhookAllowedHosts)', N',')
WHERE LTRIM(RTRIM(value)) <> N'';
IF EXISTS (SELECT 1 FROM @Hosts WHERE Host LIKE N'%[/ ]%' OR Host LIKE N'%://%')
    THROW 50400, N'WebhookAllowedHosts takes host names or IP addresses without scheme, port or path.', 1;
EXEC broker.usp_AllowedHost_Seed @Hosts;

COMMIT TRANSACTION;
GO
